# Generated by Django 4.0.6 on 2022-07-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_add_title_to_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='address',
        ),
        migrations.RemoveField(
            model_name='about',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='about',
            name='staff',
        ),
    ]
