# Generated by Django 3.2.10 on 2022-07-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_add_image_to_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение 1000х668 (файл не должен содержать русские символы в названии)', upload_to='about/', verbose_name='Картинка'),
        ),
    ]
