# Generated by Django 4.0.6 on 2022-07-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('category', models.CharField(blank=True, choices=[('Замороженная продукция', 'Замороженная продукция'), ('Свежие дары моря', 'Свежие дары моря'), ('Закуски', 'Закуски')], max_length=200, verbose_name='Категория')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('sale', models.IntegerField(blank=True, help_text='Введите размер скидки в %', verbose_name='Размер скидки %')),
                ('text', models.TextField(blank=True, verbose_name='Описание товара')),
                ('image', models.ImageField(blank=True, upload_to='catalog/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
