# Generated by Django 4.0.6 on 2022-07-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_add_price_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='price_category',
            field=models.CharField(help_text='Текст для описания цены (за кг / за шт / за 100г.)', max_length=20, verbose_name='Категория цены'),
        ),
    ]
