# Generated by Django 4.0.6 on 2022-07-10 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_add_price_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='sale',
        ),
    ]
