# Generated by Django 3.2.10 on 2022-07-11 11:33

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_delete_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Изображение 400х400 (файл не должен содержать русские символы в названии)', upload_to='catalog/', verbose_name='Фото'),
        ),
    ]
